# Generated by Django 2.2.7 on 2022-12-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='code',
        ),
    ]
