# Generated by Django 2.2.7 on 2022-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupons_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='code',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
