# Generated by Django 2.2.7 on 2022-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupons_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='validfrom',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupons',
            name='validto',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
