# Generated by Django 2.2.7 on 2022-12-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20221223_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='img_loc',
        ),
    ]
