# Generated by Django 4.1.4 on 2022-12-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_remove_coupons_img_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='slug',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
