# Generated by Django 4.1.4 on 2023-05-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupons_active_remove_coupons_timestamp_and_more'),
        ('coupons', '0007_alter_coupons_slug'),
    ]

    operations = [
    ]
