# Generated by Django 3.2.19 on 2023-06-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_merge_20230505_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coins',
            field=models.IntegerField(default=10),
        ),
    ]
