# Generated by Django 4.1.4 on 2023-06-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_coupons_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
