# Generated by Django 4.1.4 on 2023-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_coupons_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
